spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect