spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]
jwt:
  password: ${JWT_SECRET_KEY}