INSERT INTO city (id, name) VALUES
(nextval('city_seq'), '10th of Ramadan'),
(nextval('city_seq'), '15th of May'),
(nextval('city_seq'), '6th of October'),
(nextval('city_seq'), 'Abu El Matamir'),
(nextval('city_seq'), 'Abu Hummus'),
(nextval('city_seq'), 'Abu Tesht'),
(nextval('city_seq'), 'Abu Tig'),
(nextval('city_seq'), 'Akhmim'),
(nextval('city_seq'), 'Al Khankah'),
(nextval('city_seq'), 'Alexandria'),
(nextval('city_seq'), 'Arish'),
(nextval('city_seq'), 'Ashmoun'),
(nextval('city_seq'), 'Aswan'),
(nextval('city_seq'), 'Asyut'),
(nextval('city_seq'), 'Awsim'),
(nextval('city_seq'), 'Ain Sokhna'),
(nextval('city_seq'), 'Badr'),
(nextval('city_seq'), 'Baltim'),
(nextval('city_seq'), 'Banha'),
(nextval('city_seq'), 'Basyoun'),
(nextval('city_seq'), 'Biyala'),
(nextval('city_seq'), 'Belqas'),
(nextval('city_seq'), 'Beni Mazar'),
(nextval('city_seq'), 'Beni Suef'),
(nextval('city_seq'), 'Beni Ebeid'),
(nextval('city_seq'), 'Biba'),
(nextval('city_seq'), 'Bilbeis'),
(nextval('city_seq'), 'Birket El Sab'),
(nextval('city_seq'), 'Borg El Arab'),
(nextval('city_seq'), 'Borg El Burullus'),
(nextval('city_seq'), 'Bush'),
(nextval('city_seq'), 'Cairo'),
(nextval('city_seq'), 'Dahab'),
(nextval('city_seq'), 'Dairut'),
(nextval('city_seq'), 'Damanhur'),
(nextval('city_seq'), 'Damietta'),
(nextval('city_seq'), 'Dar El Salam'),
(nextval('city_seq'), 'Daraw'),
(nextval('city_seq'), 'Deir Mawas'),
(nextval('city_seq'), 'Dekernes'),
(nextval('city_seq'), 'Dendera'),
(nextval('city_seq'), 'Desouk'),
(nextval('city_seq'), 'Diarb Negm'),
(nextval('city_seq'), 'Dishna'),
(nextval('city_seq'), 'Edfu'),
(nextval('city_seq'), 'Edku'),
(nextval('city_seq'), 'El Alamein'),
(nextval('city_seq'), 'El Ayyat'),
(nextval('city_seq'), 'El Badari'),
(nextval('city_seq'), 'El Badrashein'),
(nextval('city_seq'), 'El Bagour'),
(nextval('city_seq'), 'El Balyana'),
(nextval('city_seq'), 'El Basaliya'),
(nextval('city_seq'), 'El Bayadiya'),
(nextval('city_seq'), 'El Dabaa'),
(nextval('city_seq'), 'El Delengat'),
(nextval('city_seq'), 'El Fashn'),
(nextval('city_seq'), 'El Gamaliya'),
(nextval('city_seq'), 'El Ghanayem'),
(nextval('city_seq'), 'El Hamool'),
(nextval('city_seq'), 'El Hamam'),
(nextval('city_seq'), 'El Hawamdeya'),
(nextval('city_seq'), 'El Husseiniya'),
(nextval('city_seq'), 'El Idwa'),
(nextval('city_seq'), 'El Kanayat'),
(nextval('city_seq'), 'El Mahalla El Kubra'),
(nextval('city_seq'), 'El Mahmoudiyah'),
(nextval('city_seq'), 'El Mansha'),
(nextval('city_seq'), 'El Manzala'),
(nextval('city_seq'), 'El Maragha'),
(nextval('city_seq'), 'El Matareya'),
(nextval('city_seq'), 'El Qantara'),
(nextval('city_seq'), 'El Qanater El Khayreya'),
(nextval('city_seq'), 'El Qoseir'),
(nextval('city_seq'), 'El Quseyya'),
(nextval('city_seq'), 'El Qurein'),
(nextval('city_seq'), 'El Rahmaniya'),
(nextval('city_seq'), 'El Reyad'),
(nextval('city_seq'), 'El Rhoda'),
(nextval('city_seq'), 'El Saff'),
(nextval('city_seq'), 'El Santa'),
(nextval('city_seq'), 'El Sarw'),
(nextval('city_seq'), 'El Sebaiya'),
(nextval('city_seq'), 'El Senbellawein'),
(nextval('city_seq'), 'El Shohada'),
(nextval('city_seq'), 'El Shorouk'),
(nextval('city_seq'), 'El Tor'),
(nextval('city_seq'), 'El Waqf'),
(nextval('city_seq'), 'El Wasta'),
(nextval('city_seq'), 'El Zarqa'),
(nextval('city_seq'), 'Esna'),
(nextval('city_seq'), 'Ezbet El Borg'),
(nextval('city_seq'), 'Faqous'),
(nextval('city_seq'), 'Faraskur'),
(nextval('city_seq'), 'Farshut'),
(nextval('city_seq'), 'Fayed'),
(nextval('city_seq'), 'Faiyum'),
(nextval('city_seq'), 'Fuka'),
(nextval('city_seq'), 'Girga'),
(nextval('city_seq'), 'Giza'),
(nextval('city_seq'), 'Ibsheway'),
(nextval('city_seq'), 'Ihnasya'),
(nextval('city_seq'), 'Ismailia'),
(nextval('city_seq'), 'Itay El Barud'),
(nextval('city_seq'), 'Itsa'),
(nextval('city_seq'), 'Jahina'),
(nextval('city_seq'), 'Kafr El Sheikh'),
(nextval('city_seq'), 'Kafr El Zayat'),
(nextval('city_seq'), 'Kafr El Battikh'),
(nextval('city_seq'), 'Kafr El Dawwar'),
(nextval('city_seq'), 'Kafr Saad'),
(nextval('city_seq'), 'Kafr Saqr'),
(nextval('city_seq'), 'Kafr Shukr'),
(nextval('city_seq'), 'Kafr Zarqan'),
(nextval('city_seq'), 'Kerdasa'),
(nextval('city_seq'), 'Khanka'),
(nextval('city_seq'), 'Kharga'),
(nextval('city_seq'), 'Khusus'),
(nextval('city_seq'), 'Kom Hamada'),
(nextval('city_seq'), 'Kom Ombo'),
(nextval('city_seq'), 'Luxor'),
(nextval('city_seq'), 'Maghagha'),
(nextval('city_seq'), 'Mallawi'),
(nextval('city_seq'), 'Manfalut'),
(nextval('city_seq'), 'Mansoura'),
(nextval('city_seq'), 'Mashtool El Souk'),
(nextval('city_seq'), 'Matai'),
(nextval('city_seq'), 'Menouf'),
(nextval('city_seq'), 'Marsa Alam'),
(nextval('city_seq'), 'Mersa Matruh'),
(nextval('city_seq'), 'Megan'),
(nextval('city_seq'), 'Metoubes'),
(nextval('city_seq'), 'Minya'),
(nextval('city_seq'), 'Minyet El Nasr'),
(nextval('city_seq'), 'Mit Ghamr'),
(nextval('city_seq'), 'Mit Rahina'),
(nextval('city_seq'), 'Mit Salsil'),
(nextval('city_seq'), 'Monsha''at El-Qanater'),
(nextval('city_seq'), 'Mut'),
(nextval('city_seq'), 'Mokattam'),
(nextval('city_seq'), 'Madinaty'),
(nextval('city_seq'), 'Mostakbal City'),
(nextval('city_seq'), 'Nabaroh'),
(nextval('city_seq'), 'Nasr City'),
(nextval('city_seq'), 'Nag Hammadi'),
(nextval('city_seq'), 'Naqada'),
(nextval('city_seq'), 'New Administrative Capital (NAC)'),
(nextval('city_seq'), 'New Alamein'),
(nextval('city_seq'), 'New Aswan'),
(nextval('city_seq'), 'New Akhmim'),
(nextval('city_seq'), 'New Asyut'),
(nextval('city_seq'), 'New Beni Suef'),
(nextval('city_seq'), 'New Borg El Arab'),
(nextval('city_seq'), 'New Cairo'),
(nextval('city_seq'), 'New Damietta'),
(nextval('city_seq'), 'New Faiyum'),
(nextval('city_seq'), 'New Minya'),
(nextval('city_seq'), 'New Nubariya'),
(nextval('city_seq'), 'New Salhia'),
(nextval('city_seq'), 'New Sohag'),
(nextval('city_seq'), 'New Tiba'),
(nextval('city_seq'), 'New Qena'),
(nextval('city_seq'), 'Obour'),
(nextval('city_seq'), 'Port Said'),
(nextval('city_seq'), 'Port Fuad'),
(nextval('city_seq'), 'Qaha'),
(nextval('city_seq'), 'Qallin'),
(nextval('city_seq'), 'Qalyub'),
(nextval('city_seq'), 'Qena'),
(nextval('city_seq'), 'Qift'),
(nextval('city_seq'), 'Quesna'),
(nextval('city_seq'), 'Qus'),
(nextval('city_seq'), 'Qutur'),
(nextval('city_seq'), 'Rafah'),
(nextval('city_seq'), 'Ras Burqa'),
(nextval('city_seq'), 'Ras El Bar'),
(nextval('city_seq'), 'Ras Gharib'),
(nextval('city_seq'), 'Ras Sedr'),
(nextval('city_seq'), 'Ras Shokeir'),
(nextval('city_seq'), 'Rosetta'),
(nextval('city_seq'), 'Ras El Hekma'),
(nextval('city_seq'), 'Sadat'),
(nextval('city_seq'), 'Safaga'),
(nextval('city_seq'), 'Sahel Selim'),
(nextval('city_seq'), 'Saint Catherine'),
(nextval('city_seq'), 'Samalut'),
(nextval('city_seq'), 'Samanoud'),
(nextval('city_seq'), 'Saqultah'),
(nextval('city_seq'), 'Shubra Khit'),
(nextval('city_seq'), 'Sers El Lyan'),
(nextval('city_seq'), 'Sharm El Sheikh'),
(nextval('city_seq'), 'Sherbin'),
(nextval('city_seq'), 'Sheikh Zuweid'),
(nextval('city_seq'), 'Shibin El Qanater'),
(nextval('city_seq'), 'Shibin El Kom'),
(nextval('city_seq'), 'Shubra El Kheima'),
(nextval('city_seq'), 'Sidi Barrani'),
(nextval('city_seq'), 'Sidi Salem'),
(nextval('city_seq'), 'Sinnuris'),
(nextval('city_seq'), 'Sodfa'),
(nextval('city_seq'), 'Sohag'),
(nextval('city_seq'), 'Suez'),
(nextval('city_seq'), 'Sumusta'),
(nextval('city_seq'), 'Sidi Abdel Rahman'),
(nextval('city_seq'), 'Tahta'),
(nextval('city_seq'), 'Tala'),
(nextval('city_seq'), 'Talkha'),
(nextval('city_seq'), 'Tamiya'),
(nextval('city_seq'), 'Tanta'),
(nextval('city_seq'), 'Tell El Kebir'),
(nextval('city_seq'), 'Tima'),
(nextval('city_seq'), 'Tukh'),
(nextval('city_seq'), 'Wadi El Natrun'),
(nextval('city_seq'), 'Zayn'),
(nextval('city_seq'), 'Zagazig'),
(nextval('city_seq'), 'Zefta');